/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "send_place.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

char **
place_1(placename *argp, CLIENT *clnt)
{
	static char *clnt_res;
	//this is an edit2

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PLACE,
		(xdrproc_t) xdr_placename, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
