/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "send_place.h"

bool_t
xdr_placename (XDR *xdrs, placename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}
