/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "send_coord.h"


void
send_coord_prog_1(char *host)
{
	printf("reached coordclient \n");
	CLIENT *clnt;
	char * *result_1;
	float  coord_1_arg = 10.0;

#ifndef	DEBUG
	clnt = clnt_create (host, SEND_COORD_PROG, SEND_COORD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = coord_1(&coord_1_arg, clnt);
 	printf("this is after the call to coord_1 \n");
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("this is the return from server: %s  \n", result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

/*
int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	send_coord_prog_1 (host);
exit (0);
}
*/