/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "send_place.h"
#include "send_coord.h"

//extern void send_coord_prog_1(host);
//1

char **
place_1_svc(placename *argp, struct svc_req *rqstp)
{
	static char * result;
	send_coord_prog_1 ("localhost");
	result = *argp;

	return &result;
}
