/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COORD_H_RPCGEN
#define _COORD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 255

#define SEND_COORD_PROG 0x33112217
#define SEND_COORD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define COORD 1
extern  airportList * coord_1(searchedCity *, CLIENT *);
extern  airportList * coord_1_svc(searchedCity *, struct svc_req *);
extern int send_coord_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define COORD 1
extern  airportList * coord_1();
extern  airportList * coord_1_svc();
extern int send_coord_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COORD_H_RPCGEN */
