/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "p.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
airportList *
coord_1_svc(searchedCity *argp, struct svc_req *rqstp)
{
	static airportList  result;
	struct airportNode* node = (struct airportNode*)malloc(sizeof(struct airportNode));
	/*
	 * insert server code here
	 */
	
	printf("IN THE AIRPORT SERVER");
	result->code = "123";
	result->name = "Seattle";
	result->state = "WA";
	result->distance = 5.0;
	result->next = node;	
	return &result;
}
