/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "p.h"


void
send_place_prog_1(char *host)
{
	CLIENT *clnt;
	readdir_ret  *result_1;
	placeName  place_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SEND_PLACE_PROG, SEND_PLACE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	place_1_arg = "hello";
	printf("Place client\n");
	result_1 = place_1(&place_1_arg, clnt);
	if (result_1 == (readdir_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("State: %s\n", result_1->readdir_ret_u.list.cityData.state);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	send_place_prog_1 (host);
exit (0);
}
