/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "p.h"
//extern char * airport_host;
//extern CLIENT *clntairport;
readdir_ret *
place_1_svc(placeName *argp, struct svc_req *rqstp)
{
	static readdir_ret  result;
	CLIENT *clntairport;
	airportList  *result_1;
	searchedCity  coord_1_arg;
	printf("%s\n", *argp);	
	printf("Server\n");

	result.readdir_ret_u.list.cityData.city = "Denver";
	result.readdir_ret_u.list.cityData.state = "CO";
	result.readdir_ret_u.list.cityData.lat = 40.1;
	result.readdir_ret_u.list.cityData.lon = 32.4;
	
	coord_1_arg.city = "Seattle";	
	coord_1_arg.state = "WA";
	coord_1_arg.lat = 7.0;
	coord_1_arg.lon = 7.0;
	printf("%f\n", coord_1_arg.lat);
	/*
	 * insert server code here
	 */
	if (clntairport = NULL) {
		printf("No host");
	} else {
		printf("host");
	}
	result_1 = coord_1(&coord_1_arg, clntairport);
	if (result_1 == (airportList *) NULL) {
		clnt_perror (clntairport, "call failed");
	}
	printf("AFTER RETURN FROM AIRPORT\n");
#ifndef	DEBUG
	clnt_destroy (clntairport);
#endif	 
	return &result;
}
